version: '3.8'

services:
  avalanche_be:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD
      - SPRING_PROFILES_ACTIVE=do
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/live/gameavalanche.duckdns.org:/etc/letsencrypt/live/gameavalanche.duckdns.org
      - /etc/letsencrypt/archive/gameavalanche.duckdns.org:/etc/letsencrypt/archive/gameavalanche.duckdns.org
      - /etc/letsencrypt/renewal/gameavalanche.duckdns.org.conf:/etc/letsencrypt/renewal/gameavalanche.duckdns.org.conf
