name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to Droplet
        run: |
          droplet_ip="${{ secrets.DROPLET_IP }}"
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@$droplet_ip 'mkdir -p /path/to/destination'
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ./docker-compose.yml root@$droplet_ip:/path/to/destination/docker-compose.yml
