name: Java App Deployment

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Source Code to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: 22
          source: "."  # Change this to the directory where your source code resides
          target: "/path/to/destination/on/droplet"  # Change this to the directory where you want to copy the source code

      - name: SSH into DigitalOcean Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/destination/on/droplet
            docker-compose up -d
