name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} 'bash -s' << 'EOF'
            if [ -d "/avalanche/.git" ]; then
              cd /avalanche && git pull
            else
              git clone https://github.com/nikolajsokunevs/avalanche.git /avalanche
            fi
      - name: Run docker-compose up
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} 'bash -s' << 'EOF'
            cd /avalanche
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            echo "DB_PASSWORD is: DB_PASSWORD"
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF
