name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to Droplet
        run: scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.DROPLET_IP }}:/path/to/destination

      - name: SSH into Droplet and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/destination
            docker-compose up -d
